### PR TITLE
changed exception to throwable

### PR DESCRIPTION
**Pull request by simPod**
Errors are also thrown

### CODE REVIEW

**Comment by simPod** [comment]
it's for php7 only though

**Comment by enumag** [comment]
It would be better to remove the type hint. By the way I'm planning to deprecate this package in favor of https://github.com/Arachne/EventDispatcher (this particular issue is solved there).

**Comment by mrtnzlml** [comment]
:+1: because it's used by `zenify/doctrine-migrations` package. Otherwise I am forced to stop using those packages, because it's really annoying... :)

**Comment by enumag** [comment]
I'll try to solve this tomorrow.

**Comment by enumag** [comment]
I've fixed all tests in Zenify/DoctrineMigrations and added support for Arachne/EventDispatcher (waiting for https://github.com/Kdyby/Events/pull/102). Let me know if there is something else you'd like to see in Zenify/DoctrineMigrations 2.4.

**Comment by Vrtak-CZ** [comment]
There is my try how to solve this problem https://github.com/Symnedi/EventDispatcher/pull/6

**Pull request closed without merging**
